### ISSUE TITLE
Pake Ngamux

### ISSUE THREAD

**Issue by hadihammurabi** [adrianfathurs/golangWeb#1]
Project-nya asik ni keliatannya.
Yuk cobain Ngamux supaya jadi lebih asik lagi wehehehe

https://github.com/ngamux/ngamux

**Comment by adrianfathurs** [comment]
pastinya.. oke saya belajar fundamental nya dulu baru bisa Ngamux mas wkwkwk

**Comment by hadihammurabi** [comment]
> pastinya.. oke saya belajar fundamental nya dulu baru bisa Ngamux mas wkwkwk

Ngamux juga cocok untuk belajar fundamental, Mas wehehehe...
Semangat!

**Comment by hadihammurabi** [comment]
Karena diskusi gak berlanjut, saya izin tutup issue-nya ya, Mas @adrianfathurs
